export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const ARTICLES_FETCH_SUCCEEDED = "ARTICLES_FETCH_SUCCEEDED";
export const ARTICLES_FETCH_ERROR = "ARTICLES_FETCH_ERROR";
export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const ARTICLE_FETCH_SUCCEEDED = "ARTICLE_FETCH_SUCCEEDED";
export const ARTICLE_FETCH_ERROR = "ARTICLE_FETCH_ERROR";